# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/caohy/Work/dual_line_process/xdma_bpu_tx/imports/xilinx_pcie_xdma_ref_board.xdc

# IP: ip/axis_fifo_t8/axis_fifo_t8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_fifo_t8 || ORIG_REF_NAME==axis_fifo_t8} -quiet] -quiet

# IP: ip/axis_fifo_t/axis_fifo_t.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_fifo_t || ORIG_REF_NAME==axis_fifo_t} -quiet] -quiet

# IP: ip/duc_out_fifo/duc_out_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==duc_out_fifo || ORIG_REF_NAME==duc_out_fifo} -quiet] -quiet

# IP: ip/add_duc/add_duc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==add_duc || ORIG_REF_NAME==add_duc} -quiet] -quiet

# IP: ip/mult_duc/mult_duc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_duc || ORIG_REF_NAME==mult_duc} -quiet] -quiet

# IP: ip/sub_duc/sub_duc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_duc || ORIG_REF_NAME==sub_duc} -quiet] -quiet

# IP: ip/dds_125m_q/dds_125m_q.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_125m_q || ORIG_REF_NAME==dds_125m_q} -quiet] -quiet

# IP: ip/dds_125m_i/dds_125m_i.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dds_125m_i || ORIG_REF_NAME==dds_125m_i} -quiet] -quiet

# IP: ip/rs_encoder/rs_encoder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rs_encoder || ORIG_REF_NAME==rs_encoder} -quiet] -quiet
