# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.srcs/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/mac_phy_ten_gig_eth_mac_ch0_0.xci
# IP: The module: 'mac_phy_ten_gig_eth_mac_ch0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_phy_ten_gig_eth_mac_ch0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_phy_ten_gig_eth_mac_ch0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_phy_ten_gig_eth_mac_ch0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.srcs/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/mac_phy_ten_gig_eth_mac_ch0_0.xci
# IP: The module: 'mac_phy_ten_gig_eth_mac_ch0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_phy_ten_gig_eth_mac_ch0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_phy_ten_gig_eth_mac_ch0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy/Work/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/mac_phy_ten_gig_eth_mac_ch0_0/synth/mac_phy_ten_gig_eth_mac_ch0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_phy_ten_gig_eth_mac_ch0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
