webtalk_init -webtalk_dir /home/caohy168/Work/Multiline_Synchprocess/xdma_bpu_tx/xdma_bpu_ex.sim/sim_1/behav/xsim/xsim.dir/board_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 23 03:07:30 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "da46c444-81c1-47ec-b8ed-f676a31c2a92" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "787df35f3ff049ecac8aacef5be5d688" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "102" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9980XE CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1202.169 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "84.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "467154 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1579.82_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "768960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2729311517 -regid "" -xml /home/caohy168/Work/Multiline_Synchprocess/xdma_bpu_tx/xdma_bpu_ex.sim/sim_1/behav/xsim/xsim.dir/board_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/caohy168/Work/Multiline_Synchprocess/xdma_bpu_tx/xdma_bpu_ex.sim/sim_1/behav/xsim/xsim.dir/board_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/caohy168/Work/Multiline_Synchprocess/xdma_bpu_tx/xdma_bpu_ex.sim/sim_1/behav/xsim/xsim.dir/board_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
