# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/Work/dual_line_process/xdma_bpu_rx/xdma_bpu_ex.srcs/sources_1/ip/bbtoc2h/bbtoc2h.xci
# IP: The module: 'bbtoc2h' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/Work/dual_line_process/xdma_bpu_rx/xdma_bpu_ex.gen/sources_1/ip/bbtoc2h/bbtoc2h_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbtoc2h'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caohy/Work/dual_line_process/xdma_bpu_rx/xdma_bpu_ex.srcs/sources_1/ip/bbtoc2h/bbtoc2h.xci
# IP: The module: 'bbtoc2h' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/Work/dual_line_process/xdma_bpu_rx/xdma_bpu_ex.gen/sources_1/ip/bbtoc2h/bbtoc2h_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bbtoc2h'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
