# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy/Work/dual_line_process/xdma_bpu_tx/xdma_bpu_ex.srcs/sources_1/ip/rs_encoder/rs_encoder.xci
# IP: The module: 'rs_encoder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/Work/dual_line_process/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/rs_encoder/rs_encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rs_encoder'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/caohy/Work/dual_line_process/xdma_bpu_tx/xdma_bpu_ex.srcs/sources_1/ip/rs_encoder/rs_encoder.xci
# IP: The module: 'rs_encoder' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/caohy/Work/dual_line_process/xdma_bpu_tx/xdma_bpu_ex.gen/sources_1/ip/rs_encoder/rs_encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rs_encoder'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
