#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 23 03:11:51 EDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim board_behav -key {Behavioral:sim_1:Functional:board} -tclbatch board.tcl -view /home/caohy168/Work/Multiline_Synchprocess/xdma_bpu_rx/board_behav.wcfg -log simulate.log"
xsim board_behav -key {Behavioral:sim_1:Functional:board} -tclbatch board.tcl -view /home/caohy168/Work/Multiline_Synchprocess/xdma_bpu_rx/board_behav.wcfg -log simulate.log

