# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/caohy168/Work/dual_line_process/xdma_bpu_rx/imports/pcie/xdma_bpu.xci
# IP: The module: 'xdma_bpu' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/xdma_bpu_pcie3_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip || ORIG_REF_NAME==xdma_bpu_pcie3_ip} -quiet] -quiet

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/ip_0/xdma_bpu_pcie3_ip_gt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip_gt || ORIG_REF_NAME==xdma_bpu_pcie3_ip_gt} -quiet] -quiet

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_1/xdma_v4_1_8_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/ip_0/synth/xdma_bpu_pcie3_ip_gt_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/ip_0/synth/xdma_bpu_pcie3_ip_gt.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip_gt || ORIG_REF_NAME==xdma_bpu_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/source/xdma_bpu_pcie3_ip-PCIE_X0Y0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip || ORIG_REF_NAME==xdma_bpu_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/synth/xdma_bpu_pcie3_ip_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_1/xdma_v4_1_8_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/xdma_bpu_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bpu'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/source/xdma_bpu_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bpu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/synth/xdma_bpu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bpu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/caohy168/Work/dual_line_process/xdma_bpu_rx/imports/pcie/xdma_bpu.xci
# IP: The module: 'xdma_bpu' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/xdma_bpu_pcie3_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip || ORIG_REF_NAME==xdma_bpu_pcie3_ip} -quiet] -quiet

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/ip_0/xdma_bpu_pcie3_ip_gt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip_gt || ORIG_REF_NAME==xdma_bpu_pcie3_ip_gt} -quiet] -quiet

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_1/xdma_v4_1_8_blk_mem_64_reg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_reg_be} -quiet] -quiet

# IP: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_8_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/ip_0/synth/xdma_bpu_pcie3_ip_gt_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/ip_0/synth/xdma_bpu_pcie3_ip_gt.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip_gt || ORIG_REF_NAME==xdma_bpu_pcie3_ip_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/source/xdma_bpu_pcie3_ip-PCIE_X0Y0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_bpu_pcie3_ip || ORIG_REF_NAME==xdma_bpu_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_0/synth/xdma_bpu_pcie3_ip_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_1/xdma_v4_1_8_blk_mem_64_reg_be_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/ip_2/xdma_v4_1_8_blk_mem_64_noreg_be_ooc.xdc

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/xdma_bpu_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bpu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/source/xdma_bpu_pcie3_us_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bpu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/caohy168/Work/xdma_bpu_ex.gen/sources_1/ip/xdma_bpu/synth/xdma_bpu_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bpu'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
